title: maximiliankraft.github.io
description: "Diese Webseite stellt Unterrichtsmaterialien zur Verfügung"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://maximiliankraft.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  maximiliankraft
markdown: CommonMarkGhPages
# Build settings
theme: minima
# plugins:
  # - jekyll-feed
  # - jekyll-sitemap # for seo
  # - jekyll-redirect-from
  # - jekyll-analytics

header_pages:
- # inidcates that no page shall be listed as headerpage
#  - schueler.md
#  - about.md

minima:
  skin: classic # dark

#jekyll_analytics:
#  GoogleAnalytics:
#    id: G-4X0SVGFBJC  # Required - replace with your tracking id
#    anonymizeIp: true # Optional - Default: false - set to true for anonymized tracking

# Collections
collections:
  pages:
    output: true
    permalink: /:path/

# Permalink structure
permalink: /:title/

# Default front matter
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
exclude:
  - upload.sh
  - secrets.sh